### PR TITLE
update to HDF5's sudden deprecation of boolean API version options

### PR DESCRIPTION
**Pull request by benson31**

### CODE REVIEW

**Comment by davidHysom** [comment]
Is this why my builds are failing?

CMake Error at /usr/WS2/hysom/lbann/build/gnu.Release.pascal.llnl.gov/hdf5/stamp/HDF5-configure-Release.cmake:16 (message):
  Command failed: 1

   '/usr/tce/packages/cmake/cmake-3.12.1/bin/cmake' '-DCMAKE_C_COMPILER=/usr/tce/packages/gcc/gcc-7.3.0/bin/gcc' '-DCMAKE_C_FLAGS=-DLBANN_SET_EL_RNG -O3 -march=broadwell -mtune=broadwell -ldl' '-DCMAKE_CXX_COMPILER=/usr/tce/packages/gcc/gcc-7.3.0/bin/g++' '-DCMAKE_CXX_FLAGS=-DLBANN_SET_EL_RNG -O3 -march=broadwell -mtune=broadwell -ldl' '-DBUILD_SHARED_LIBS=ON' '-DBUILD_TESTING=OFF' '-DHDF5_GENERATE_HEADERS=ON' '-DHDF5_BUILD_CPP_LIB:BOOL=OFF' '-DHDF5_BUILD_EXAMPLES:BOOL=OFF' '-DHDF5_BUILD_FORTRAN:BOOL=OFF' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DCMAKE_COMMAND:FILEPATH=/usr/tce/packages/cmake/cmake-3.12.1/bin/cmake' '-DCMAKE_INSTALL_PREFIX:PATH=/usr/WS2/hysom/lbann/build/gnu.Release.pascal.llnl.gov/install' '-DHDF5_ENABLE_PARALLEL:BOOL=ON' '-DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON' '-DHDF5_USE_110_API_DEFAULT:BOOL=OFF' '-DHDF5_USE_112_API_DEFAULT:BOOL=OFF' '-DHDF5_USE_16_API_DEFAULT:BOOL=OFF' '-DHDF5_USE_18_API_DEFAULT:BOOL=ON' '-GUnix Makefiles' '/usr/WS2/hysom/lbann/build/gnu.Release.pascal.llnl.gov/hdf5/src'
   
gnu.Release.pascal.llnl.gov/hdf5/stamp/HDF5-configure-err.log:
CMake Error at CMakeLists.txt:646 (set_property):
  set_property could not find CACHE variable DEFAULT_API_VERSION.  Perhaps it
  has not yet been created.

note: this is in: build/gnu.Release.pascal.llnl.gov/hdf5/src/CMakeLists.txt

**Comment by timmoon10** [comment]
We need to make Conduit an optional dependency of LBANN. It's really bringing too much baggage and instability.

**Comment by benson31** [comment]
@davidHysom Yes.

**Comment by bvanessen** [comment]
Remember to separate the difference between Conduit and HDF5 in the conversation here.  At the time being, I do not see making Conduit optional for LBANN as it provides a reasonable way to manage in memory data structures inside of the data store.  Now that doesn’t mean that we have to include HDF5 in every build or configuration.  HDF5 is used by the JAG and Hydra data readers and can be made as an optional setup inside of LBANN.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by davidHysom** [comment]
HDF5 is appears broken again. Fresh lbann checkout this morning, build failed:

CMake Deprecation Warning at CMakeLists.txt:52 (cmake_policy):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


git executable: /usr/tce/packages/git/git-2.8.3/bin/git
CMake Warning (dev) at /usr/tce/packages/cmake/cmake-3.12.1/share/cmake/Modules/FindHDF5.cmake:449 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable HDF5_ROOT is set to:

    /usr/WS2/hysom/lbann/build/gnu.Release.pascal.llnl.gov/install

  Environment variable HDF5_ROOT is set to:

    /usr/WS2/hysom/lbann/build/gnu.Release.pascal.llnl.gov/install/bin

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  cmake/thirdparty/SetupHDF5.cmake:65 (include)
  cmake/Setup3rdParty.cmake:120 (include)
  CMakeLists.txt:114 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/thirdparty/SetupHDF5.cmake:203 (message):
  h5cc -showconfig call failed
Call Stack (most recent call first):
  cmake/Setup3rdParty.cmake:120 (include)
  CMakeLists.txt:114 (include)
________________________________

**Pull request merged**
