### PR TITLE
Nheads diff

### PR DESCRIPTION
**Pull request by JaeseungYeom**
This PR shows exactly what changes are made in PR #743.
This allows us to see the changes clearly and also enables us to make inline review comments on where most relevant.

### CODE REVIEW

**Comment by andy-yoo** [comment]
The changes seem to be OK.
I see conflicts on data_reader_triplet.hpp|cpp, though.
I left these two files for references. 
Are they removed now?

**Comment by JaeseungYeom** [comment]
The original files are renamed to the new files first, and overwritten by your new files (which I backed up in advance) such that the changes are highlighted.

**Comment by andy-yoo** [comment]
I think the change can be merged as I am confident that the new code works, but I see some conflicts in some of the files we worked on. This is your PR, so I will leave the honor of resolving the conflicts.

**Comment by timmoon10** [comment]
PR #743 has been merged, so it's safe to close this.

**Pull request closed without merging**
