### PR TITLE
FC layer doesn't need output dimensions at instantiation.

### PR DESCRIPTION
**Pull request by timmoon10**
This fixes a bug introduced in PR #685. See PR #693 for a discussion and an alternative solution.

### CODE REVIEW

**Comment by JaeseungYeom** [comment]
or add `if (params.num_neurons_is_num_labels())`
and set num_neurons there by calling `dr->get_num_labels()`

**Comment by timmoon10** [comment]
I think this would be spaghetti code. I don't see why we should apply this check since we check again during layer setup.

**Comment by JaeseungYeom** [comment]
What I am suggesting is to gather the num neuron setup capabilities to one place rather than making it duplicate or eliminating sanity check.

**Comment by timmoon10** [comment]
We check the neuron tensor dimensions after setting up each layer: https://github.com/LLNL/lbann/blob/a1b23401e3c288360c0310a127b8f5dbea94b6e8/src/layers/layer.cpp#L742

**Comment by JaeseungYeom** [comment]
I don't think simply checking tensor dimensions is sufficient here since there are multiple ways to set up num neurons. When a check fails, it is not clear whether the user has initiated a capability unsupported by the reader, misused the capability, or simply put a wrong dimension.

**Comment by bvanessen** [comment]
I understand the discussion going on here.  Once this has been tested, I am going to merge it in for a needed code release so that we have a working AlexNet.  Once some of the work in the I/O subsystem is put to bed we are going to address the challenges of both the data reader and the prototext.

**Pull request merged**
