### PR TITLE
Parallelize computation of Gaussian random numbers

### PR DESCRIPTION
**Pull request by timmoon10**
This replaces calls to `El::Gaussian` with an OpenMP-parallelized loop. Running the ATOM WAE on a Pascal node, I see a 3.6x speedup in the Gaussian layers.

I haven't properly tested this yet and I'd like to implement some basic normality tests in Catch. But deadlines being what they are, we can merge this in if we're willing to accept the risk of a bug.

### CODE REVIEW

**Comment by timmoon10** [comment]
I've added unit tests to estimate whether `gaussian_fill` is actually outputting Gaussian numbers. It runs the [Anderson-Darling test](https://en.wikipedia.org/wiki/Anderson%E2%80%93Darling_test) three times for each matrix type and fails if it gets three 0.05 significance events. We do this for O(50) matrix types, so the probability of a fluky failure is <2%.

 In retrospect I think this approach is both overkill and insufficient. I'm not sure if it can detect some likely failures like duplicated values. But in any case, it gives us a sign that `gaussian_fill` is producing something that roughly looks like the desired distribution.

**Comment by timmoon10** [comment]
It looks like [`fugaku-develop`](https://github.com/LLNL/lbann/tree/fugaku-develop) fails Bamboo due to a `-Werror` complaint. See: https://github.com/LLNL/lbann/blob/17cd056a1ce198d8b8397f89d811fc7d01c08095/src/data_readers/data_reader.cpp#L225

To keep this PR minimal, I've rebased and changed it to merge into `develop`.

[Bamboo is in progress](https://lc.llnl.gov/bamboo/browse/LBANN-TIM359-2).

**Comment by timmoon10** [comment]
[Bamboo is being uncooperative](https://lc.llnl.gov/bamboo/browse/LBANN-TIM362-1). I'm still in the process of debugging.

**Comment by timmoon10** [comment]
[Latest Bamboo build](https://lc.llnl.gov/bamboo/browse/LBANN-TIM362-6).

The test failures for "Testing gaussian_fill" are fixed with https://github.com/LLNL/Elemental/pull/118. I think the compiler errors are related to Catch failures, since the compiler script also runs the Catch tests. I think this is ready to merge. If we want to be sure, we can rebuild Hydrogen for Bamboo and rerun the tests.

**Comment by timmoon10** [comment]
[No new Bamboo failures](https://lc.llnl.gov/bamboo/browse/LBANN-TIM362-7). This is ready to go.

**Review by benson31 — APPROVED** [review]
Seems reasonable.

**Pull request merged**
