### PR TITLE
Remove unused drivers

### PR DESCRIPTION
**Pull request by benson31**
The remaining drivers are moved out of `model_zoo`, where they really had no business ever being.

The CMake changes are also implemented. There should be no observable difference to the average user.

### CODE REVIEW

**Review by tbennun — APPROVED** [review]
LGTM

**Review by bvanessen — CHANGES_REQUESTED** [review]
Under review.

**Review by fiedorowicz1 — APPROVED** [review]
👍

**Comment by tbennun** [comment]
lbann_inf can be mimicked by changing num_epochs to 0

**Review by ndryden — APPROVED** [review]
No functionality is lost, confusion is reduced. :shipit:

**Review by bvanessen — APPROVED** [review]

**Pull request merged**
