### PR TITLE
Support specifying random seeds in Python

### PR DESCRIPTION
**Pull request by ndryden**
For `resnet.py` this adds a `--random-seed` argument.

### CODE REVIEW

**Comment by ndryden** [comment]
This will need updates, presumably, if the random seed gets moved around in the trainer refactor.

Also, we should look at abstracting common arguments to Python drivers so every script doesn't have to duplicate them.

**Comment by timmoon10** [comment]
> Also, we should look at abstracting common arguments to Python drivers so every script doesn't have to duplicate them.

Isn't this handled in `lbann.contrib.args`?

**Comment by ndryden** [comment]
Maybe. I was thinking things like mini-batch size, etc.

**Comment by timmoon10** [comment]
Yea, I see it would be helpful to implement a function like `add_model_arguments`.

**Pull request merged**
