### PR TITLE
Fc neurons

### PR DESCRIPTION
**Pull request by davidHysom**
added functionality: the fully connected layer preceeding a softmax layer no longer needs to specify num_neurons; instead, use the field: 'num_neurons_is_num_labels: true'

### CODE REVIEW

**Comment by timmoon10** [comment]
The `num_neurons_is_num_labels` option for the fully-connected layer duplicates the `num_neurons_from_data_reader` option for layers. I'm also rather uneasy that this approach only deals the fully-connected layer and doesn't handle tensor dimensions. A more general approach would be functionality so that the base layer class can take the dimensions of another layer (see #320). I don't think we should make widespread changes to our prototexts without some more discussion.

**Comment by davidHysom** [comment]
Sam: changes to the data store should not have been in this PR.
Tim: I didn't know about "num_neurons_from_data_reader;" I wish someone had mentioned that when I first discussed my proposed changes several weeks ago.
I will remove this PR.

**Comment by timmoon10** [comment]
I'm sorry for not noticing the conflict earlier. Our documentation also does need a lot of work, we also tripped up in #297... It may be worthwhile going through our prototext format, clearing out deprecated functionality, and designing a stable set of supported features.

**Comment by davidHysom** [comment]
"The num_neurons_is_num_labels option for the fully-connected layer duplicates the num_neurons_from_data_reader option for layers"
After checking, this is different functionality. "num_neurons_from_data_reader" uses linearized_data_size.
"num_neurons_is_num_labels" set the number of neurons to be the number of labels.

**Comment by JaeseungYeom** [comment]
Is this PR still active?

**Comment by davidHysom** [comment]
There are several conflicts, both in the code and the above comments, so I am closing this PR.

**Pull request closed without merging**
