### PR TITLE
Update spack_recipes/build_lbann.sh

### PR DESCRIPTION
**Pull request by mcneish1**
Fixes:
 * debug flags now propagate to elemental
 * use correct mpi on ray/sierra

Run with e.g. 
`bsub -G guests lrun -T4 ./lbann [lbann options here]` - sierra
`bsub -G guests -n 4 mpirun -np 4 ./lbann [lbann options here]` - ray

`jsrun` is much slower without additional arguments, `mpirun` apparently requires ~200 characters of extra parameters to work.

`~/.spack/linux/packages.yaml` for current (as of writing) mpi+cuda:
```packages:
    all:
        providers:
            mpi: [spectrum-mpi]
    spectrum-mpi:
        buildable: False
        version: [2018.04.27]
        paths:
            spectrum-mpi@2018.04.27 arch=linux-rhel7-ppc64le: /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-2018.04.27
    cudnn:
        buildable: False
        version: [7.0]
        paths:
            cudnn@7.0 arch=linux-rhel7-pp64le: /usr/tce/packages/cudnn/cudnn-7.0-cuda-9.0

    cuda:
        buildable: False
        version: [9.2.64]
        paths:
            cuda@9.2.64 arch=linux-rhel7-pp64le: /usr/tce/packages/cuda/cuda-9.2.64```

### CODE REVIEW

**Comment by bvanessen** [comment]
Something looks off in this PR.  It is trying to write 84 files.

**Comment by mcneish1** [comment]
I know, I screwed up rebase. Trying to fix it now

**Comment by mcneish1** [comment]
Ok, back to where it was. The merge conflict is just the pascal flag, going to fix that now.

**Comment by bvanessen** [comment]
Corey, I just fixed the merge conflicts.  Please see if the merged code works for you.

**Comment by mcneish1** [comment]
Yep that's what I was going to do.

I'm a little hesitant to say this is good to go now, seeing as I haven't tried it with the recent mpi/cuda default changes.

**Comment by mcneish1** [comment]
Okay this is good to go now. I updated the initial comment for the spack profile to use.

**Pull request merged**
