### PR TITLE
[MERGE] Updates to the build system

### PR DESCRIPTION
**Pull request by benson31**
This PR streamlines the CMake a little bit better than it was. It also updates things for the new era of CUDA as a first-class language in CMake.

I've almost certainly broken all of your scripts. Sorry (not really, but if it makes you feel better, you can believe that).

I have gotten things building on LC; CPU builds on catalyst and GPU builds on Surface. Both seem to work. The superbuild isn't 100% complete; just basic builds of most TPLs. If you want/need a more advanced build of something, use builds you have lying around from old builds of LBANN for now. For the GPU build, you will need CUB and cuDNN from somewhere, and optionally NCCL2. The CMake will verify NCCL2 vs NCCL1.

NOTE: I have changed around many macros. E.g., \_\_LIB_\<NAME\> is probably "LBANN_HAS_\<NAME\>" now. I brute-forced my way through this with command-line sed, so please check that I didn't ruin everything. The defined macros are recorded in \<build-dir\>/lbann-config.hpp. Also, LBANN_DATATYPE is not a number any more; it's now a word (e.g. "float") and this is typedef'd to "lbann::DataType" in the same lbann-config.hpp.

TODO:
- [x] Finish robustifying "superbuild" CMake stuff
- [ ] Add NVPROF and VTUNE support back in.
- [ ] Complete install target (LBANNConfig.cmake.in, etc.)
- [x] Test on Ray

WHAT I NEED FROM YOU: If any of the dependencies have minimum/maximum/specific versions, please let me know. Currently NCCL is the only one I know. If any of you are aware of non-LBANN apps that use liblbann, please let me know.

I'm sure there's more to say. If you have problems, comment here, email me, chat me, or catch me at the weekly meeting.

Cheers!

### CODE REVIEW

**Comment by benson31** [comment]
This is at a point where a basic run of the superbuild now works (no fancy BLAS or anything; just CNPY, CUB, Hydrogen, OpenCV, and Protobuf). It still needs more testing, but the review should begin now that all the main functionality is there. Some details in the superbuild are still being worked out, but should not be much more work.

**Comment by bvanessen** [comment]
@JaeseungYeom can you please check to see if your use case with the patches for OpenBLAS are working on Ray.  The entire build worked fine for me on Ray, but I don't know that I had the patches included.

**Comment by benson31** [comment]
The RPATH stuff should be ok now, on both linux and mac.

**Comment by JaeseungYeom** [comment]
I will look into it.
Jaeseung


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by ndryden** [comment]
I built successfully on Catalyst, but LBANN seems to be running terribly slowly. Not sure why.

Here's what I used for it:
```/usr/workspace/wsb/brain/utils/toss3/cmake-3.9.6/bin/cmake ../superbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./catalyst.llnl.gov -DLBANN_SB_BUILD_CNPY=ON -DLBANN_SB_BUILD_HYDROGEN=ON -DLBANN_SB_BUILD_OPENCV=ON -DLBANN_SB_BUILD_PROTOBUF=ON -DLBANN_SB_BUILD_LBANN=ON```

**Comment by benson31** [comment]
I claim that this is ready to merge.

@ndryden, can you try building with jpeg-turbo enabled and see if that benchmarks ok?

**Comment by bvanessen** [comment]
I just checked out the latest version and it builds on my mac and on LC with both the main script and spack.

**Comment by JaeseungYeom** [comment]
I am getting the following error while building elemental using intel/18.0.0 on quartz
CMake Error at cmake/modules/FindAndVerifyLAPACK.cmake:155 (message):
  Could not determine BLAS suffix!
Probably the suffix is not set. It should probably be '_'.

**Comment by benson31** [comment]
@JaeseungYeom which blas library are you using? MKL? This is actually probably something else going wrong. If you could send me $BUILD_DIR/CMakeFiles/CMakeOutput.log and $BUILD_DIR/CMakeFiles/CMakeError.log, that could help as well.

**Comment by benson31** [comment]
I have been told by numerous people to "just merge already". So here we go!

**Pull request merged**
