### PR TITLE
Build script

### PR DESCRIPTION
**Pull request by davidHysom**
The build fails if any of the following are given in isolation:
  --disable-cuda
  --disable-aluminum
  --disable-aluminum-with-nccl
Currently you must specify multiple flags, e.g: --disable-cuda --disable-aluminum
This is annoying and error prone. The build script is modified so that disabling cuda will automatically disable aluminum, and vice versa

### CODE REVIEW

**Comment by ndryden** [comment]
Aluminum (should) work perfectly fine without CUDA. I think if you disable CUDA, you should disable the NCCL and MPI-CUDA backends for Aluminum, but not Aluminum as a whole.

**Comment by benson31** [comment]
Right, CUDA should work without Aluminum and Aluminum should work without CUDA. If they don't, issues should be filed documenting the failures so we can fix them.

**Comment by davidHysom** [comment]
> Right, CUDA should work without Aluminum and Aluminum should work without CUDA. If they don't, issues should be filed documenting the failures so we can fix them.

This is the error I got running the build script:
$ build_lbann_lc.sh --disable-aluminum
CMake Error at CMakeLists.txt:313 (message):
  CUDA support not found.  Disabling CUDA the features.

I don't know if it works if you don't use the build script -- because I don't know how to build lbann without the script.

**Comment by benson31** [comment]
That happens if it can't find a cuda compiler. I don't know why that happens. I'll look into it. In the meantime, perhaps try "ml opt cudatoolkit/9.2" and then rerun the script.

**Comment by davidHysom** [comment]
Closing in light of Tom and Nikoli's comments. It should be possible to build without cuda and with aluminum -- there's something else going on with the build script -- apparently it's not finding the nvcc compiler with certain flags.

**Comment by davidHysom** [comment]
I thought I closed it without merging -- at least that was my intent. It should not have been merged.

________________________________

**Comment by bvanessen** [comment]
I believe that you pulled this PR onto other PRs and when you committed them, it include these changes.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by ndryden** [comment]
This PR was closed without merging. Not sure if it was merged via other PRs.

**Pull request closed without merging**
