### PR TITLE
Objective function refactor

### PR DESCRIPTION
**Pull request by timmoon10**
This pull request adds functionality to compute separate statistics for each execution mode. This will be especially useful for LTFB.

It also adds the EvalType typedef, currently defined as a double. This is intended to provide a consistent datatype for objective function values, metrics, and timings that is independent of DataType.

### CODE REVIEW

**Comment by davidHysom** [comment]
Are we going to continue to use typedefs, instead of "using?" I believe Jae-Seung changed some of his typedefs to using. Is there a consensus that we should be consistent? Or, does it really matter?

**Comment by ndryden** [comment]
I would prefer `using`. It's the same as `typedef`, but (to me at least) more clear, and, it also supports templates (i.e. `template <typename T> using foo = bar<T>`).

**Comment by timmoon10** [comment]
Would it be worthwhile changing DataType to a `using` as well?

**Comment by ndryden** [comment]
If we want to clean up all the uses of `typedef`, then sure, but I wouldn't do it piecemeal unless you're touching the code already.

**Comment by davidHysom** [comment]
If there's a consensus, I can attempt to use clang-tidy to modify our entire codebase (develop) to transition from typedefs to usings

**Comment by bvanessen** [comment]
Yes let’s switch to using and the EvalType for metrics and objective functions.


Brian C. Van Essen

vanessen1@llnl.gov<mailto:vanessen1@llnl.gov>

(w) 925-422-9300

(c) 925-290-5470

---

Sent from my iPhone

On Dec 22, 2017, at 3:18 PM, davidHysom <notifications@github.com<mailto:notifications@github.com>> wrote:


If there's a consensus, I can attempt to use clang-tidy to modify our entire codebase (develop) to transition from typedefs to usings

**Comment by bvanessen** [comment]
Dave, do you want to run clang-tidy on the pull request before it gets merged, or have us merge it and then clean it up?

**Comment by bvanessen** [comment]
Oh, nevermind, I reread the comments about typedef and using and I think that we should get this merged and then switch everything over from typedef to using.

**Comment by davidHysom** [comment]
Thinking it's best if you merge, then I'll clean.

________________________________

**Comment by bvanessen** [comment]
Okay, I am downloading it now to build and if it compiles clean, I will merge it tonight.

**Pull request merged**
