### PR TITLE
oneDNN support on CPU

### PR DESCRIPTION
**Pull request by benson31**

### CODE REVIEW

**Review by timmoon10 — CHANGES_REQUESTED** [review]
Overall looks good. The only critical change is that we don't initialize the workspace for the GPU model-parallel impl.

**Comment by benson31** [comment]
It occurred to me that I have not yet run Bamboo on this. This is in progress. I will comment again when it's through.

**Review by timmoon10 — APPROVED** [review]
:shipit: , pending no Bamboo problems.

**Comment by benson31** [comment]
@bvanessen @mrwyattii This is passing Bamboo for me.

**Review by bvanessen — APPROVED** [review]

**Pull request merged**
